---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team-beta-subnamespaces
  namespace: dev-team-beta-ns
spec:
  serviceAccountName: flux
  interval: 5m
  sourceRef:
    kind: GitRepository
    name: dev-team-beta
  prune: true
  path: /base/subnamespaces
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev-team-beta-resources
  namespace: dev-team-beta-ns
spec:
  serviceAccountName: flux
  interval: 5m
  dependsOn:
    - name: dev-team-beta-subnamespaces
      namespace: dev-team-beta-ns
  sourceRef:
    kind: GitRepository
    name: dev-team-beta
  prune: true
  path: /base/manifests
